name: Application Testing

on:
  workflow_call:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt libraries
        run: sudo apt install gettext -y

      - name: Setup Node.js version from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --silent

      - name: Install translations
        run: yarn localize

      - name: Run Jest tests
        run: yarn test

      - name: Run TypeScript checks
        run: npx tsc
