name: "Master Workflow"

on:
  workflow_call:
    inputs:
      languages:
        description: "Languages to analyze"
        required: false
        default: "javascript-typescript" # Space-separated string instead of JSON
        type: string
      build_mode:
        description: "Build mode for CodeQL analysis"
        required: false
        default: "none"
        type: string

jobs:
  app-test:
    uses: gqcorneby/workflows/.github/workflows/app-test.yml@main

  codeql-analysis:
    uses: gqcorneby/workflows/.github/workflows/codeql.yml@main
    with:
      languages: ${{ inputs.languages }}
      build_mode: ${{ inputs.build_mode }}

  pr-build-diff:
    uses: gqcorneby/workflows/.github/workflows/bundlemon-build-size.yml@main

